#pragma once

#define EGParameterCode_GAMEID           (255)
#define EGParameterCode_ACTORNR          (254)
#define EGParameterCode_TARGET_ACTORNR   (253)
#define EGParameterCode_ACTOR_LIST       (252)
#define EGParameterCode_PROPERTIES       (251)
#define EGParameterCode_BROADCAST        (250)
#define EGParameterCode_ACTOR_PROPERTIES (249)
#define EGParameterCode_GAME_PROPERTIES  (248)
#define EGParameterCode_CACHE            (247)
#define EGParameterCode_RECEIVER_GROUP   (246)
#define EGParameterCode_DATA             (245)
#define EGParameterCode_CODE             (244)
#define EGParameterCode_GROUP            (240)
#define EGParameterCode_REMOVE           (239)
#define EGParameterCode_ADD              (238)
